version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.prod
    ports:
      - "8000:8000"  # Adjust if needed based on your setup
    volumes:
      - .:/bolo_rides  # Optional for development; remove in production for better performance
