# Use the official Python image from the Docker Hub
FROM python:3.12-slim


# Set the working directory (where the code will be running from in the container)
RUN mkdir /bolo_rides
WORKDIR /bolo_rides

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

COPY . /bolo_rides/



RUN pip install -r requirements.txt

COPY . .

EXPOSE 8000




# Command to run your application (adjust as necessary)
CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]
