import 'bootstrap/dist/css/bootstrap.min.css';
import Header from './components/header';
import Footer from './components/footer';
import { AuthProvider } from './authContext';
import  ElvisForm from './elvisform/page';
import ElvisHistory from './elvis-history/page';

export const metadata = {
  title: 'Create Next App', // Corrected the typo from "Creaate" to "Create"
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang='en'>
      <body>
        <AuthProvider>
          <Header />
          <div className="container">
            {children}
            <ElvisForm />
           
           
          </div>
          <Footer />
        </AuthProvider>
      </body>
    </html>
  );
}