import 'bootstrap/dist/css/bootstrap.min.css';
import Header from './components/header';
import Footer from './components/footer';
import { AuthProvider } from './authContext';

export const metadata = {
  title: 'Create Next App', 
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang='en'>
      <body>
        <AuthProvider>
          <Header />
          <div className="container">
            {children}  
          </div>
          <Footer />
        </AuthProvider>
      </body>
    </html>
  );
}