# Generated by Django 5.1.4 on 2025-01-04 05:26

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicallevinussection',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalsergesection',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='elvissection',
            name='history_type',
        ),
        migrations.RemoveField(
            model_name='levinussection',
            name='history_type',
        ),
        migrations.RemoveField(
            model_name='sergesection',
            name='history_type',
        ),
        migrations.CreateModel(
            name='EditHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('previous_data', models.JSONField()),
                ('current_data', models.JSONField()),
                ('edited_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
        ),
        migrations.DeleteModel(
            name='HistoricalElvisSection',
        ),
        migrations.DeleteModel(
            name='HistoricalLevinusSection',
        ),
        migrations.DeleteModel(
            name='HistoricalSergeSection',
        ),
    ]
