# Generated by Django 5.1.4 on 2025-01-23 03:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='elvissection',
            name='temp_field',
        ),
        migrations.RemoveField(
            model_name='levinussection',
            name='temp_field',
        ),
        migrations.RemoveField(
            model_name='sergesection',
            name='temp_field',
        ),
    ]
