# Generated by Django 5.1.4 on 2025-01-09 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_historicallevinussection_history_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='elvissection',
            name='balance_amount_due',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='elvissection',
            name='daily_rental_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='elvissection',
            name='number_of_rental_days',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='elvissection',
            name='paid_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='elvissection',
            name='total_amount_due',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='levinussection',
            name='balance_amount_due',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='levinussection',
            name='daily_rental_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='levinussection',
            name='number_of_rental_days',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='levinussection',
            name='paid_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='levinussection',
            name='total_amount_due',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='sergesection',
            name='balance_amount_due',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='sergesection',
            name='daily_rental_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='sergesection',
            name='number_of_rental_days',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='sergesection',
            name='paid_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='sergesection',
            name='total_amount_due',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
    ]
