# Generated by Django 5.1 on 2024-09-26 02:04

import django.db.models.deletion
import django.utils.timezone
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_elvissection_transaction_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalElvisSection',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('date_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('destination', models.CharField(max_length=100)),
                ('rental_rate_amount', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True)),
                ('expenses', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True)),
                ('expense_tag', models.CharField(max_length=100)),
                ('management_fee_accruals', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True)),
                ('driver_income', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True)),
                ('net_income', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True)),
                ('transaction', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True)),
                ('comments', models.CharField(default='leave message', max_length=100)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Elvis Section',
                'verbose_name_plural': 'historical Elvis Sections',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalLevinusSection',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('date_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('destination', models.CharField(max_length=100)),
                ('rental_rate_amount', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True)),
                ('expenses', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True)),
                ('expense_tag', models.CharField(max_length=100)),
                ('management_fee_accruals', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True)),
                ('driver_income', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True)),
                ('net_income', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True)),
                ('transaction', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True)),
                ('comments', models.CharField(default='leave message', max_length=100)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Levinus Section',
                'verbose_name_plural': 'historical Levinus Sections',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalSergeSection',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('date_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('destination', models.CharField(max_length=100)),
                ('rental_rate_amount', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True)),
                ('expenses', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True)),
                ('expense_tag', models.CharField(max_length=100)),
                ('management_fee_accruals', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True)),
                ('driver_income', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True)),
                ('net_income', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True)),
                ('transaction', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True)),
                ('comments', models.CharField(default='leave message', max_length=100)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Serge Section',
                'verbose_name_plural': 'historical Serge Sections',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
