# Generated by Django 5.1.4 on 2025-01-09 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_elvissection_balance_amount_due_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='elvissection',
            name='daily_rental_amount',
        ),
        migrations.RemoveField(
            model_name='levinussection',
            name='daily_rental_amount',
        ),
        migrations.RemoveField(
            model_name='sergesection',
            name='daily_rental_amount',
        ),
    ]
