# Generated by Django 5.1.4 on 2025-01-24 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_elvissection_thoughts_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elvissection',
            name='comments',
            field=models.CharField(blank=True, default='leave message', max_length=100),
        ),
        migrations.AlterField(
            model_name='elvissection',
            name='destination',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='elvissection',
            name='expense_tag',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='levinussection',
            name='comments',
            field=models.CharField(blank=True, default='leave message', max_length=100),
        ),
        migrations.AlterField(
            model_name='levinussection',
            name='destination',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='levinussection',
            name='expense_tag',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='sergesection',
            name='comments',
            field=models.CharField(blank=True, default='leave message', max_length=100),
        ),
        migrations.AlterField(
            model_name='sergesection',
            name='destination',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='sergesection',
            name='expense_tag',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
