# Generated by Django 5.1.4 on 2025-01-13 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_elvissection_daily_rental_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='elvissection',
            name='temp_field',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='levinussection',
            name='temp_field',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='sergesection',
            name='temp_field',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
