# Generated by Django 5.1.4 on 2025-01-24 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_elvissection_comments_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elvissection',
            name='destination',
            field=models.CharField(blank=True, default='No destination', max_length=100),
        ),
        migrations.AlterField(
            model_name='levinussection',
            name='destination',
            field=models.CharField(blank=True, default='No destination', max_length=100),
        ),
        migrations.AlterField(
            model_name='sergesection',
            name='destination',
            field=models.CharField(blank=True, default='No destination', max_length=100),
        ),
    ]
