# Generated by Django 5.1.4 on 2025-01-13 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_elvissection_temp_field_levinussection_temp_field_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='elvissection',
            name='temp_field',
        ),
        migrations.RemoveField(
            model_name='levinussection',
            name='temp_field',
        ),
        migrations.RemoveField(
            model_name='sergesection',
            name='temp_field',
        ),
    ]
