# Generated by Django 5.1.4 on 2025-01-24 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_elvissection_thoughts_levinussection_thoughts_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='elvissection',
            name='thoughts',
        ),
        migrations.RemoveField(
            model_name='levinussection',
            name='thoughts',
        ),
        migrations.RemoveField(
            model_name='sergesection',
            name='thoughts',
        ),
    ]
