# Generated by Django 5.1.4 on 2025-01-13 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_elvissection_temp_field_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elvissection',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='levinussection',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='sergesection',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
