# Generated by Django 5.1.4 on 2025-01-29 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_remove_elvissection_thoughts_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='elvissection',
            name='thoughts',
            field=models.CharField(default='leave message', max_length=100),
        ),
        migrations.AddField(
            model_name='levinussection',
            name='thoughts',
            field=models.CharField(default='leave message', max_length=100),
        ),
        migrations.AddField(
            model_name='sergesection',
            name='thoughts',
            field=models.CharField(default='leave message', max_length=100),
        ),
    ]
